---
title: "CodeBook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The run_analysis.R script performs the getting and cleaning the UCI HAR Dataset task as specified in the course project's definition. The script contains five steps to execute data tidy job as described below:

### 1. Download the zip data file

- Download the zip data file to "./Data/UCI HAR Dataset" folder, unzip it.

### 2. Extracts only the measurements on the mean and standard deviation for each measurement.

- Get activities labels and features
```
activityLabels <- read.table("./Data/UCI HAR Dataset/activity_labels.txt")
activityLabels[,2] <- as.character(activityLabels[,2])
features <- read.table("./Data/UCI HAR Dataset/features.txt")
features[,2] <- as.character(features[,2])
```
- Get all mean and standard deviation features and update the feature names and uses descriptive activity names to name the activities in the data set
```
desiredFeature <- grep("*mean*|*std*", features[,2])
desiredFeature.names <- features[desiredFeature,2]
desiredFeature.names = gsub('-mean', 'Mean', desiredFeature.names)
desiredFeature.names = gsub('-std', 'Std', desiredFeature.names)
desiredFeature.names <- gsub('[-()]', '', desiredFeature.names)
```
- Load the train dataset and only extract mean and STD  
```
train <- read.table("./Data/UCI HAR Dataset/train/X_train.txt")[desiredFeature]
trainActivities <- read.table("./Data/UCI HAR Dataset/train/Y_train.txt")
trainSubjects <- read.table("./Data/UCI HAR Dataset/train/subject_train.txt")
train <- cbind(trainSubjects, trainActivities, train)
```
- Load the test dataset and only extract mean and STD
```
test <- read.table("./Data/UCI HAR Dataset/test/X_test.txt")[desiredFeature]
testActivities <- read.table("./Data/UCI HAR Dataset/test/Y_test.txt")
testSubjects <- read.table("./Data/UCI HAR Dataset/test/subject_test.txt")
test <- cbind(testSubjects, testActivities, test)
```
### 3. Merges the training and the test sets to create one data set.
- Merge train and test dataset and add labels
```
allData <- rbind(train, test)
```
### 4. turn activities & subjects into factors with meaningful labels;Appropriately labels the data set with descriptive variable names. 
```
colnames(allData) <- c("subject", "activity", desiredFeature.names)
allData$activity <- factor(allData$activity, levels = activityLabels[,1], labels = activityLabels[,2])
allData$subject <- as.factor(allData$subject)
```
### 5. creates a second, independent tidy data set(CleanData.txt) with the average of each variable for each activity and each subject.
```
allData.melted <- melt(allData, id = c("subject", "activity"))
allData.mean <- dcast(allData.melted, subject + activity ~ variable, mean)
write.table(allData.mean, "./Data/UCI HAR Dataset/CleanData.txt", row.names = FALSE, quote = FALSE)
```